languaje: bash
dist: trusty
os:
  - linux

compiler:
  - gcc
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
      
script: 
  - ./mBedSeedMap.sh ./tutorial/seatoxin.fa ./tutorial/seatoxin.ref
